### ISSUE TITLE
Demo site graph slowly scrolls off the bottom of the screen

### ISSUE THREAD

**Issue by paul-hammant** [public-accountability/oligrapher#133]
After cloning and `npm install` I do `npm run serve`

... then I navigate to localhost:8000/dev/ I see the graph scroll off the bottom of the page, yet I'm not touching the mouse or keyboard. See hastily made screencap with the chart nearly off the bottom of the page after a couple of seconds:

![Screenshot 2023-04-02 8 58 58 PM](https://user-images.githubusercontent.com/82182/229376179-49f86709-969e-410a-a9f1-b3517af12ab5.png)

Pretty sure that shouldn't happen. I'm using Chrome v110.0.5481.181 (Official Build) (64-bit), It does the same for Firefox too.

**Comment by josephlacey** [comment]
This should be fixed with the above PR.
