### ISSUE TITLE
jq dependency not found

### ISSUE THREAD

**Issue by betsydupuis** [public-accountability/oligrapher#136]
**Steps to reproduce**
```
$ npm install

$ npm run dev

$ npx sass app/oligrapher.scss build/oligrapher.css --style=compressed
```

This is the error upon build.
<img width="365" alt="Screenshot 2024-07-02 at 5 11 54 PM" src="https://github.com/public-accountability/oligrapher/assets/2096627/e5af9835-2448-4046-ac59-86207f12f3fc">

`npm install jq --save` does not resolve the issue. There appears to a never ended mess of poorly resolved dependencies in jq.

[jq appears to no longer be maintained](https://github.com/logicalparadox/jq) and only used in the build files. It might be easier to remove it and replace it with something else.

**Comment by aepyornis** [comment]
this is jq: https://github.com/jqlang/jq

**Comment by josephlacey** [comment]
Thanks @betsydupuis!  Merged.

And thanks @aepyornis for the input.
