### ISSUE TITLE
Using Oligrapher in a static gen'd site

### ISSUE THREAD

**Issue by paul-hammant** [public-accountability/oligrapher#83]
Is there example code as to how to embed in Jekyll for a static GitHub-Pages deployment?

I'm wondering if it is even possible..

**Comment by aepyornis** [comment]
Hey @paul-hammant  I don't know the particulars of Jekyll or GitHub pages, but if you are you using maps hosted on LittleSis.org you can use an `<iframe>` to embed the map: 

```
<iframe height="600" width="700" scrolling="no" style="border: 0px; overflow: hidden;" src="https://littlesis.org/maps/6574-the-banks-corporations-financing-new-coal-power-plants-in-vietnam/embedded"></iframe>
```

**Comment by paul-hammant** [comment]
That's great to hear.

But long term I'd want such intel to be canonically held in Git, for a bunch of benefits - Git is a History Retaining Merkle Tree. It's cloneable. It can receive contributions from anon people ("pull requests" and similar).

**Comment by aepyornis** [comment]
I just want to make sure I understand what you mean here. by storing the 'intel in git' do you mean you'd like to store the _content_ of an oligrapher map in a git repository?

**Comment by paul-hammant** [comment]
Everything needed to recreate the (read only) interactive experience in Git, yes. YAML, JSON, CSV, RDF triples.   Changes can come via pull requests, if needs be.   

Here - https://github.com/thecdil/timelinejs-template - is CDIL (Idaho), taking 'timeline-js3' by Knight Lab (Northwestern) into git cloneable goodness. Just like that, would be great :)

**Comment by aepyornis** [comment]
Here is a simple repo with an oligrapher map on a static page https://github.com/aepyornis/oligrapher-static-example

**Comment by paul-hammant** [comment]
Thanks a bunch!!!!
